### ISSUE TITLE
Extensão requerida para o php 8

### ISSUE THREAD

**Issue by curruwilla** [robsonvleite/cropper#14]
Para não ter problemas com o cropper no php 8 é necessário 'descomentar' a extensão:
**extension=gd**

no arquivo php.ini

**Comment by alexnogueirasilva** [comment]
não consigo da o composer require coffeecode/cropper com a versão 8 setada como resolver ?

**Comment by robsonvleite** [comment]
A extensão GB já está no requisito do componente.
