### ISSUE TITLE
[BUG REPORT] Nova miniatura por dia

### ISSUE THREAD

**Issue by wilderamorim** [robsonvleite/cropper#5]
Quando é gerada uma nova miniatura você atualiza a página e ela permanece, mas se no outro dia acessar, é gerada uma nova miniatura.
Todo dia que acessa gera uma nova miniatura.

**Comment by robsonvleite** [comment]
Parece que foi resolvido Wilder, vou fechar e se continuar você abre novamente fechado?

**Comment by wilderamorim** [comment]
Já foi sim, valeu!
