### ISSUE TITLE
file_exists

### ISSUE THREAD

**Issue by cairocampos** [robsonvleite/cropper#9]
Opa, quando se usa a func **file_exists()** não funciona em http/https, nesse caso, passaria o caminho absoluto para funcionar, ex: /var/www...
Mas devido o método retornar o caminho da imagem, passando o caminho absoluto para o construtor o chrome bloquearia devido ser arquivo de um recurso local ex: C://wamp/www/site/imagem.jpg

**Comment by robsonvleite** [comment]
Correto Cairo, para trabalhar com o Cropper tens que passar o caminho relativo da imagem.
